cookie:
  expiry_days: 10
  key: giggigis
  name: giggigis
credentials:
  usernames:
    Luigi:
      email: jeggino@gmail.com
      logged_in: False
      name: Luigi Giugliano
      password: Platinum_79

    daan:
      email: jeggino@gmail.com
      logged_in: False
      name: Daan
      password: Daan_2024
preauthorized:
  emails: melsby@gmail.com
