cookie:
  expiry_days: 0
  key: ceppo
  name: capocchia
credentials:
  usernames:
    Luigi:
      email: jeggino@gmail.com
      logged_in: False
      name: Luigi Giugliano
      password: Platinum_79

    Mischa:
      email: jeggino@gmail.com
      logged_in: False
      name: Mischa van der Hout
      password: veld_2024

    Maarten:
      email: jeggino@gmail.com
      logged_in: False
      name: Maarten
      password: veld_2024

    daan:
      email: jeggino@gmail.com
      logged_in: False
      name: Daan
      password: Daan_2024
preauthorized:
  emails: melsby@gmail.com
